freemarker:
  expose-request-attribute: true

upload:
  path: C:/Users/User/Desktop/PizzaShop/upload

logging:
  file: logging/log.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    application.service.impl:
      ProductService: INFO
      UserProfileService: INFO
      TypeProductService: INFO
      BasketService: INFO
    ROOT: ERROR
    org:
      springframework: ERROR
  appender:

spring:
  profiles:
    active: "devNoSql"
---
spring:
  profiles: devSql
  -datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  -jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
  -mail:
    host: smtp.gmail.com
    port: 465
    auth: true
    username: valerii.vasylkivskyi@gmail.com
    password: xladik19
    starttls:
      enable: true
    transport:
      protocol: smtps
    debug: true

---
spring:
  profiles: devNoSql
  -datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  -jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
  -mail:
    host: smtp.gmail.com
    port: 465
    auth: true
    username: valerii.vasylkivskyi@gmail.com
    password: xladik19
    starttls:
      enable: true
    transport:
      protocol: smtps
    debug: true

