create table user_profile (
    id bigint generated by default as identity,
    active boolean, bonus integer,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);
create table user_profile_roles (
    user_profile_id bigint not null,
    roles varchar(255),
    foreign key (user_profile_id) references user_profile(id)
);
create table product (
    id bigint generated by default as identity,
    code integer,
    description varchar(255),
    name varchar(255),
    price double,
    type varchar(255),
    primary key (id)
);
create table product_size (
    product_id bigint not null,
    sizes varchar(255),
    foreign key (product_id) references product(id)
);
